// High-ROI TELC B1 listening additions.
// These are deliberately answer-changing words/chunks rather than broad topic vocabulary.
// They complement the corpus deck and are prioritised for aural recognition.
export type ListeningPowerWord={id:string;de:string;es:string;pron:string;chunk:string;roi:number;category:string;listening:number};
const raw:[string,string,string,string,number][]=[
['ausfallen','cancelarse / no realizarse','ÁUS-fa-len','Der Zug fällt heute aus.',100],
['fällt aus','se cancela / no funciona','felt ÁUS','Der Kurs fällt morgen aus.',100],
['nicht mehr','ya no','nijt MEA','Der Bus fährt heute nicht mehr.',100],
['noch nicht','todavía no','noj NIJT','Der Zug ist noch nicht angekommen.',100],
['erst ab','recién / solo a partir de','eRST ap','Die Praxis öffnet erst ab 15 Uhr.',100],
['stattdessen','en su lugar','SHTAT-de-sen','Stattdessen fährt ein Bus.',100],
['gesperrt','cerrado / bloqueado al tránsito','gue-SHPERT','Die Straße ist wegen Bauarbeiten gesperrt.',100],
['verschoben','aplazado / pospuesto','fer-SHÓ-ben','Der Termin wurde auf Freitag verschoben.',99],
['stattfinden','tener lugar / realizarse','SHTAT-fin-den','Die Veranstaltung findet am Samstag statt.',99],
['entfallen','suprimirse / cancelarse','ent-FÁ-len','Der Halt in Potsdam entfällt.',99],
['geändert','cambiado / modificado','gue-ÉN-dert','Der Fahrplan wurde geändert.',99],
['nur noch','solo queda / solamente todavía','nur NOJ','Es gibt nur noch zwei Plätze.',99],
['mindestens','como mínimo','MÍN-des-tens','Sie müssen mindestens 18 Jahre alt sein.',99],
['höchstens','como máximo','HÖJ-stens','Die Fahrt dauert höchstens 30 Minuten.',99],
['insgesamt','en total','ÍNS-gue-zamt','Insgesamt kostet es 25 Euro.',98],
['jeweils','cada uno / respectivamente','YÉ-vails','Die Busse fahren jeweils um halb und um voll.',98],
['ungefähr','aproximadamente','UN-gue-fea','Die Fahrt dauert ungefähr eine Stunde.',98],
['mehr als','más de','mea als','Mehr als 50 Personen haben teilgenommen.',98],
['weniger als','menos de','VÉ-ni-guer als','Es kostet weniger als 20 Euro.',98],
['fast','casi','fast','Der Zug hat fast eine Stunde Verspätung.',98],
['bereits','ya / ya anteriormente','be-RÁITS','Die Tickets sind bereits ausverkauft.',98],
['allerdings','sin embargo / eso sí','Á-ler-dings','Am Samstag ist geöffnet, allerdings nur bis zwölf.',98],
['sondern','sino','ZÓN-dern','Nicht am Montag, sondern am Dienstag.',98],
['obwohl','aunque','op-VÓL','Obwohl es regnet, findet das Fest statt.',97],
['trotzdem','aun así / sin embargo','TROTS-dem','Es regnet. Trotzdem fährt der Bus.',97],
['wegen','a causa de / por','VÉ-guen','Wegen Bauarbeiten kommt es zu Verspätungen.',100],
['deshalb','por eso','DÉS-halp','Der Zug ist voll. Deshalb nehmen wir den Bus.',97],
['während','mientras / durante','VÉ-rent','Während der Ferien bleibt das Büro geschlossen.',97],
['vorher','antes','FÓR-hea','Bitte melden Sie sich vorher an.',97],
['anschließend','a continuación / después','ÁN-shli-sent','Anschließend gibt es ein gemeinsames Essen.',97],
['inzwischen','mientras tanto / entretanto','in-TSVÍ-shen','Inzwischen ist die Straße wieder frei.',96],
['vorbei','terminado / pasado','for-BÁI','Die Aktion ist am Sonntag vorbei.',96],
['planmäßig','según lo previsto / puntual','PLÁN-mé-siJ','Der ICE kommt planmäßig an.',100],
['voraussichtlich','previsiblemente','for-ÁUS-zijt-lij','Der Zug kommt voraussichtlich 20 Minuten später.',99],
['Verspätung','retraso','fer-SHPÉ-tung','Der Zug hat 30 Minuten Verspätung.',100],
['rechtzeitig','a tiempo','REJT-tsái-tij','Bitte kommen Sie rechtzeitig zum Termin.',97],
['pünktlich','puntual','PÜNKT-lij','Der Bus fährt pünktlich um acht.',98],
['ab sofort','desde ahora / con efecto inmediato','ap zo-FORT','Die neue Regel gilt ab sofort.',98],
['bis einschließlich','hasta inclusive','bis ÁIN-shli-s-lij','Das Angebot gilt bis einschließlich Freitag.',98],
['abgesehen von','aparte de / salvo','AP-gue-ze-en fon','Abgesehen von Sonntag ist täglich geöffnet.',96],
['kostenlos','gratis','KÓS-ten-los','Der Eintritt ist kostenlos.',99],
['ermäßigt','con descuento / tarifa reducida','er-MÉ-siJt','Studenten zahlen den ermäßigten Preis.',98],
['ausverkauft','agotado','ÁUS-fer-kauft','Die Vorstellung ist bereits ausverkauft.',99],
['verfügbar','disponible','fer-FÜG-bar','Es sind noch Plätze verfügbar.',98],
['Anmeldung','inscripción','ÁN-mel-dung','Eine Anmeldung ist erforderlich.',98],
['erforderlich','necesario / obligatorio','er-FÓR-der-lij','Ein Ausweis ist erforderlich.',99],
['ausnahmsweise','excepcionalmente','ÁUS-nams-vái-ze','Heute schließen wir ausnahmsweise früher.',98],
['geöffnet','abierto','gue-ÖF-net','Das Museum ist sonntags geöffnet.',99],
['geschlossen','cerrado','gue-SHLÓ-sen','Die Praxis bleibt morgen geschlossen.',100],
['abgesagt','cancelado','AP-gue-zakt','Das Konzert wurde abgesagt.',100],
['Ersatz','reemplazo / sustitución','er-ZATS','Es gibt einen Ersatzbus.',99],
['Ersatzverkehr','servicio de transporte sustitutorio','er-ZATS-fer-kea','Zwischen den Bahnhöfen gibt es Ersatzverkehr.',100],
['umsteigen','hacer transbordo','UM-shtái-guen','In Köln müssen Sie umsteigen.',99],
['einsteigen','subir / abordar','ÁIN-shtái-guen','Bitte steigen Sie jetzt ein.',98],
['aussteigen','bajarse','ÁUS-shtái-guen','Sie müssen an der nächsten Haltestelle aussteigen.',98],
['Richtung','dirección','RIJ-tung','Nehmen Sie den Zug Richtung Zentrum.',98],
['Haltestelle','parada','HÁL-te-shté-le','Die nächste Haltestelle ist Alexanderplatz.',98],
['Abfahrt','salida','AP-fart','Die Abfahrt ist um 18:20 Uhr.',99],
['Ankunft','llegada','ÁN-kunft','Die Ankunft ist für 19 Uhr geplant.',99],
['Gleisänderung','cambio de andén / vía','GLÁIS-en-de-rung','Bitte beachten Sie die Gleisänderung.',100],
['verlegt','trasladado / cambiado de lugar','fer-LÉKT','Der Kurs wurde in Raum 12 verlegt.',99],
['fällt weg','se elimina / se suprime','felt VEK','Die erste Stunde fällt weg.',100],
['findet nicht statt','no se realiza','fin-det NIJT shtat','Der Markt findet heute nicht statt.',100],
['gilt nur','solo es válido / aplica solo','guilt NUR','Das Ticket gilt nur am Wochenende.',99],
['spätestens','a más tardar','SHPÉ-tes-tens','Bitte kommen Sie spätestens um 17 Uhr.',99],
['frühestens','como muy pronto','FRÜ-es-tens','Sie können frühestens am Montag kommen.',99],
['zunächst','primero / inicialmente','tsu-NÉJST','Zunächst fahren Sie bis zum Hauptbahnhof.',96],
['schließlich','finalmente','SHLÍS-lij','Schließlich erreichen Sie das Zentrum.',95],
['etwa','aproximadamente','ÉT-va','Die Reparatur dauert etwa zwei Stunden.',97],
['knapp','casi / apenas','knap','Die Fahrt dauert knapp eine Stunde.',97],
['doppelt','el doble','DÓ-pelt','Am Wochenende kostet es doppelt so viel.',97],
['Hälfte','mitad','HÉLF-te','Kinder zahlen die Hälfte.',97],
['zunehmen','aumentar','TSU-ne-men','Die Zahl der Besucher nimmt zu.',96],
['abnehmen','disminuir','AP-ne-men','Der Verkehr hat deutlich abgenommen.',96],
['steigt','sube / aumenta','shtáikt','Der Preis steigt ab Oktober.',97],
['sinkt','baja / disminuye','zinkt','Die Temperatur sinkt in der Nacht.',97],
['empfohlen','recomendado','em-PFÓ-len','Eine Reservierung wird empfohlen.',96],
['verpflichtend','obligatorio','fer-PFLIJ-tent','Die Anmeldung ist verpflichtend.',98],
['verboten','prohibido','fer-BÓ-ten','Parken ist hier verboten.',99],
['erlaubt','permitido','er-LÁUPT','Fahrräder sind im Zug erlaubt.',98],
['beachten','tener en cuenta / prestar atención','be-ÁJ-ten','Bitte beachten Sie die neuen Öffnungszeiten.',99],
['beziehungsweise','o respectivamente / más precisamente','be-TSÍ-ungs-vái-ze','Montag beziehungsweise Dienstag ist möglich.',95],
['weder … noch','ni … ni','VÉ-der noj','Weder Busse noch Bahnen fahren.',100],
['sowohl … als auch','tanto … como','zo-VÓL als auj','Sowohl Erwachsene als auch Kinder können teilnehmen.',97],
['entweder … oder','o … o','ent-VÉ-der ó-der','Sie können entweder bar oder mit Karte zahlen.',97],
['nicht nur … sondern auch','no solo … sino también','nijt nur zón-dern auj','Es gibt nicht nur Kurse, sondern auch Beratung.',97],
['aufgrund','debido a','ÁUF-grunt','Aufgrund des Wetters bleibt der Park geschlossen.',99],
['trotz','a pesar de','trots','Trotz des Regens findet das Konzert statt.',98],
['innerhalb','dentro de','Í-ner-halp','Bitte antworten Sie innerhalb einer Woche.',96],
['außerhalb','fuera de','ÁU-ser-halp','Außerhalb der Öffnungszeiten ist niemand erreichbar.',96],
['vorübergehend','temporalmente','for-Ü-ber-gue-ent','Der Eingang ist vorübergehend geschlossen.',99],
['wieder geöffnet','abierto nuevamente','VÍ-der gue-öf-net','Ab Montag ist das Schwimmbad wieder geöffnet.',98],
['erreichbar','localizable / accesible','er-RÁIJ-bar','Die Praxis ist telefonisch erreichbar.',96],
['zuständig','responsable / competente','TSU-shtén-dij','Dafür ist das Bürgeramt zuständig.',96],
['benötigen','necesitar','be-NÖ-ti-guen','Sie benötigen einen gültigen Ausweis.',97],
['mitbringen','traer consigo','MIT-brin-guen','Bitte bringen Sie Ihren Pass mit.',98],
['abholen','recoger','AP-ho-len','Die Karten können an der Kasse abgeholt werden.',98],
['zurückgeben','devolver','tsu-RÜK-gue-ben','Das Gerät muss morgen zurückgegeben werden.',96],
['vereinbaren','concertar / acordar','fer-ÁIN-ba-ren','Bitte vereinbaren Sie vorher einen Termin.',97],
['absagen','cancelar','AP-za-guen','Sie müssen den Termin rechtzeitig absagen.',99],
['bestätigen','confirmar','be-SHTÉ-ti-guen','Bitte bestätigen Sie Ihre Teilnahme.',97],
['teilnehmen','participar','TÁIL-ne-men','Nur angemeldete Personen können teilnehmen.',97],
['ausgeschlossen','excluido','ÁUS-gue-shló-sen','Kinder unter sechs Jahren sind ausgeschlossen.',96],
['unter sechs','menor de seis','ÚN-ter zeks','Kinder unter sechs fahren kostenlos.',98],
['über 18','mayor de 18','Ü-ber ajt-tsén','Das Angebot gilt nur für Personen über 18.',98],
['pro Person','por persona','pro per-ZÓN','Der Eintritt kostet zwölf Euro pro Person.',98],
['im Voraus','por adelantado','im for-ÁUS','Die Tickets müssen im Voraus bezahlt werden.',97],
['vor Ort','en el lugar','for ORT','Sie können auch vor Ort bezahlen.',97],
['bar bezahlen','pagar en efectivo','bar be-TSÁ-len','Sie können nur bar bezahlen.',98],
['mit Karte','con tarjeta','mit KÁR-te','Die Gebühr kann mit Karte bezahlt werden.',98]
];
export const LISTENING_POWER:ListeningPowerWord[]=raw.map((x,i)=>({id:`lp:${x[0].toLowerCase()}`,de:x[0],es:x[1],pron:x[2],chunk:x[3],roi:x[4],category:'listening-power',listening:999-i}));
