import{LISTENING_POWER}from'./listeningPower';
const KEY='telcb1-listening-power-v1';
type State={known:string[];review:string[]};
function state():State{try{return{known:[],review:[],...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{known:[],review:[]}}}
function save(s:State){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('telcb1-listening-power',{detail:s}))}
function speak(t:string){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.82;speechSynthesis.speak(u)}catch{}}
function esc(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
let i=0,show=false;
function queue(){const s=state();return[...LISTENING_POWER].sort((a,b)=>(s.known.includes(a.id)?1:0)-(s.known.includes(b.id)?1:0)||b.roi-a.roi)}
function render(){const host=document.getElementById('listening-power-modal');if(!host)return;const s=state(),q=queue(),v=q[i%q.length],n=s.known.length,total=LISTENING_POWER.length,pct=Math.round(n/total*100);host.innerHTML=`<div class="lp-backdrop"></div><section class="lp-panel"><button class="lp-close" aria-label="Cerrar">×</button><div class="lp-eye">🎧 LISTENING POWER · ${n}/${total} DOMINADOS</div><h1>Palabras que cambian la respuesta.</h1><p class="lp-sub">Entrena significado + reconocimiento auditivo. Priorizadas para TELC B1 Listening, no vocabulario general.</p><div class="lp-progress"><i style="width:${pct}%"></i></div><div class="lp-card"><span>ROI ${v.roi}</span>${show?`<small>SIGNIFICADO</small><h2>${esc(v.es)}</h2><blockquote>${esc(v.chunk)}</blockquote><button class="lp-hear">🔊 Escuchar frase</button>`:`<small>ESCUCHA / RECONOCE</small><h2>${esc(v.de)}</h2><p>¿Qué significa en este tipo de anuncio o conversación TELC?</p><button class="lp-reveal">Revelar</button>`}</div><div class="lp-actions"><button class="lp-no">Todavía no</button><button class="lp-yes">Sí, instantáneo</button></div><p class="lp-note">Objetivo: reconocerlo sin traducir mentalmente. Chunks como <b>nicht mehr</b>, <b>erst ab</b> o <b>fällt aus</b> cuentan como una unidad.</p></section>`;
 host.querySelector('.lp-close')?.addEventListener('click',close);host.querySelector('.lp-backdrop')?.addEventListener('click',close);host.querySelector('.lp-reveal')?.addEventListener('click',()=>{show=true;speak(v.chunk);render()});host.querySelector('.lp-hear')?.addEventListener('click',()=>speak(v.chunk));host.querySelector('.lp-no')?.addEventListener('click',()=>mark(false));host.querySelector('.lp-yes')?.addEventListener('click',()=>mark(true));}
function mark(ok:boolean){const v=queue()[i%queue().length],s=state();s.known=s.known.filter(x=>x!==v.id);s.review=s.review.filter(x=>x!==v.id);if(ok)s.known.push(v.id);else s.review.push(v.id);save(s);i++;show=false;render()}
function open(){let host=document.getElementById('listening-power-modal');if(!host){host=document.createElement('div');host.id='listening-power-modal';document.body.appendChild(host)}host.style.display='block';show=false;render()}
function close(){const h=document.getElementById('listening-power-modal');if(h)h.style.display='none'}
function install(){if(document.getElementById('listening-power-launch'))return;const b=document.createElement('button');b.id='listening-power-launch';b.innerHTML='🎧 <b>Listening Power</b><small>High-ROI TELC</small>';b.addEventListener('click',open);document.body.appendChild(b);const st=document.createElement('style');st.textContent=`#listening-power-launch{position:fixed;right:22px;bottom:22px;z-index:900;border:0;border-radius:16px;padding:11px 16px;background:#20152f;color:#fff;box-shadow:0 12px 35px #20152f33;cursor:pointer;font:700 14px system-ui}#listening-power-launch small{display:block;font-size:9px;opacity:.65;margin-top:2px}.lp-backdrop{position:fixed;inset:0;background:#160d22aa;backdrop-filter:blur(6px);z-index:990}.lp-panel{position:fixed;z-index:991;inset:5vh max(16px,calc((100vw - 720px)/2));max-height:90vh;overflow:auto;background:#faf8fd;border-radius:28px;padding:34px;color:#251832;box-shadow:0 30px 90px #0005;font-family:system-ui}.lp-close{position:absolute;right:20px;top:16px;border:0;background:transparent;font-size:30px}.lp-eye{font-size:11px;font-weight:900;letter-spacing:.12em;color:#765c91}.lp-panel h1{font-size:30px;margin:8px 0}.lp-sub{font-size:15px;line-height:1.5;color:#6c6273}.lp-progress{height:8px;background:#e9e2ef;border-radius:9px;overflow:hidden;margin:20px 0}.lp-progress i{display:block;height:100%;background:#8f75aa}.lp-card{background:white;border:1px solid #e9e1ef;border-radius:22px;padding:30px;min-height:270px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center}.lp-card>span{align-self:flex-end;font-size:11px;font-weight:900;color:#765c91}.lp-card small{font-weight:900;letter-spacing:.1em;color:#8d8195}.lp-card h2{font-size:38px;margin:16px 0}.lp-card p,.lp-card blockquote{font-size:17px;line-height:1.5}.lp-card button,.lp-actions button{border:0;border-radius:13px;padding:12px 18px;font-weight:800;cursor:pointer}.lp-reveal,.lp-hear{background:#2a1d39;color:white}.lp-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.lp-no{background:#eee8f2}.lp-yes{background:#dff3e6}.lp-note{font-size:12px;color:#776d7d;line-height:1.5}@media(max-width:700px){#listening-power-launch{right:12px;bottom:72px}.lp-panel{inset:2vh 10px;padding:24px 18px;max-height:96vh}.lp-panel h1{font-size:25px}.lp-card{padding:20px;min-height:240px}.lp-card h2{font-size:30px}}`;document.head.appendChild(st)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
