import{SENTENCES,LISTENING}from'./data';

type State={sentenceIndex:number;sentenceHistory:number[];listeningIndex:number;listeningHistory:{index:number;correct:boolean;answer:number}[]};
const KEY='telcb1-exercise-history-v1';
const defaults:State={sentenceIndex:0,sentenceHistory:[],listeningIndex:0,listeningHistory:[]};
function load():State{try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...defaults}}}
function save(s:State){localStorage.setItem(KEY,JSON.stringify(s))}
function esc(s:any){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function speak(t:string,rate=.82){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=rate;speechSynthesis.speak(u)}
function uniq(xs:number[]){return[...new Set(xs)]}
let state=load(),mode:'sentences'|'listening'|null=null,reviewIndex:number|null=null,sentenceShown=false,listenPre=true,listenAnswer:number|null=null,listenScript=false,applying=false;

function style(){if(document.getElementById('exercise-history-style'))return;const x=document.createElement('style');x.id='exercise-history-style';x.textContent=`
.exerciseHistoryBar{display:flex;gap:10px;align-items:center;justify-content:flex-end;margin:0 0 14px;flex-wrap:wrap}.exerciseHistoryBar button,.exerciseHistoryModal button{border:1px solid rgba(74,52,103,.18);background:#fff;border-radius:12px;padding:9px 13px;cursor:pointer;font:inherit}.exerciseHistoryBar .ehProgress{margin-right:auto;font-size:12px;font-weight:800;letter-spacing:.04em;opacity:.62}.exerciseHistoryModal{position:fixed;inset:0;z-index:99999;background:rgba(26,18,38,.45);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:18px}.exerciseHistoryPanel{width:min(720px,100%);max-height:82vh;overflow:auto;background:#faf8f5;border-radius:24px;padding:22px;box-shadow:0 24px 80px #0003}.exerciseHistoryHead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.exerciseHistoryHead h2{margin:0}.exerciseHistoryItem{width:100%;text-align:left!important;display:flex;justify-content:space-between;gap:16px;margin:8px 0;padding:13px 15px!important}.exerciseHistoryItem span{opacity:.65;font-size:12px}.exerciseReviewBadge{display:inline-flex;padding:5px 9px;border-radius:999px;background:rgba(74,52,103,.08);font-size:11px;font-weight:800;margin-bottom:10px}.exerciseHistoryEmpty{padding:30px;text-align:center;opacity:.6}.exerciseHistoryBack{margin-bottom:12px}.ehRight{color:#237a4b}.ehWrong{color:#a03c3c}@media(max-width:700px){.exerciseHistoryPanel{padding:16px;border-radius:20px}.exerciseHistoryItem{display:block}.exerciseHistoryItem span{display:block;margin-top:4px}}
`;document.head.appendChild(x)}
function current(){const main=document.querySelector('main');if(!main)return null;const txt=main.textContent||'';if(txt.includes('GERMAN BRAIN ORDER'))return'sentences';if(txt.includes('PRIORIDAD MÁXIMA')&&txt.includes('Listening'))return'listening';return null}
function card(){return document.querySelector(mode==='sentences'?'.sentenceCard':'.listenCard') as HTMLElement|null}
function bar(){let b=document.querySelector('.exerciseHistoryBar') as HTMLElement|null;if(b)return b;const c=card();if(!c)return null;b=document.createElement('div');b.className='exerciseHistoryBar';c.parentElement?.insertBefore(b,c);return b}
function updateBar(){const b=bar();if(!b||!mode)return;const idx=mode==='sentences'?state.sentenceIndex:state.listeningIndex;const total=mode==='sentences'?SENTENCES.length:LISTENING.length;const count=mode==='sentences'?state.sentenceHistory.length:state.listeningHistory.length;b.innerHTML=`<span class="ehProgress">EJERCICIO ${Math.min(idx+1,total)} DE ${total} · ${count} HECHOS</span><button data-eh="history">Historial (${count})</button>`}
function addXp(n:number){try{const p=JSON.parse(localStorage.getItem('telcb1')||'{}');p.xp=(p.xp||0)+n;localStorage.setItem('telcb1',JSON.stringify(p))}catch{}}
function renderSentence(){const c=card();if(!c)return;const idx=reviewIndex??Math.min(state.sentenceIndex,SENTENCES.length-1),d=SENTENCES[idx] as any;updateBar();c.innerHTML=`${reviewIndex!==null?'<div class="exerciseReviewBadge">REPASANDO HISTORIAL · tu progreso nuevo queda guardado</div>':''}<small>ORDEN ESPAÑOL → ESTRUCTURA ALEMANA</small><h2>${esc(d[1])}</h2>${sentenceShown?`<div class="answer"><b>${esc(d[2])}</b><button data-eh="sentence-audio">🔊 Escuchar</button></div>`:`<button class="primary" data-eh="sentence-show">Ver alemán</button>`}<button class="ghost" data-eh="sentence-next">${reviewIndex!==null?'Volver a ejercicios nuevos':'Siguiente'} ›</button>`}
function renderListening(){const c=card();if(!c)return;const idx=reviewIndex??Math.min(state.listeningIndex,LISTENING.length-1),d=LISTENING[idx] as any;updateBar();if(reviewIndex!==null){const old=state.listeningHistory.find(x=>x.index===idx);listenPre=false;listenAnswer=old?.answer??null}c.innerHTML=`${reviewIndex!==null?'<div class="exerciseReviewBadge">REPASANDO HISTORIAL · no cambia tus estadísticas</div>':''}<span class="pill">${esc(d[0])}</span>${listenPre?`<h2>Pre-learn</h2><div class="chips">${(d[5]||[]).map((k:string)=>`<button data-eh="keyword" data-text="${esc(k)}">🔊 ${esc(k)}</button>`).join('')}</div><button class="primary" data-eh="pre-done">Ya las reconozco</button>`:`<div class="audioBox"><button data-eh="listen-normal">▶ Normal</button><button data-eh="listen-slow">🔊 Lento</button></div><h3>${esc(d[2])}</h3><div class="options">${d[3].map((o:string,j:number)=>`<button data-eh="answer" data-j="${j}" class="${listenAnswer===j?(j===d[4]?'right':'wrong'):''}">${esc(o)}</button>`).join('')}</div>${listenAnswer!==null?`<button class="ghost" data-eh="script">${listenScript?'Ocultar transcript':'Ver transcript'}</button>${listenScript?`<p class="transcript">${esc(d[1])}</p>`:''}<button class="primary" data-eh="listen-next">${reviewIndex!==null?'Volver a ejercicios nuevos':'Siguiente'}</button>`:''}`}`}
function render(){if(applying||!mode)return;applying=true;try{style();mode==='sentences'?renderSentence():renderListening()}finally{applying=false}}
function openHistory(){if(!mode)return;document.querySelector('.exerciseHistoryModal')?.remove();const m=document.createElement('div');m.className='exerciseHistoryModal';const history=mode==='sentences'?state.sentenceHistory:state.listeningHistory.map(x=>x.index);m.innerHTML=`<div class="exerciseHistoryPanel"><div class="exerciseHistoryHead"><div><small>REPASO</small><h2>Historial de ${mode==='sentences'?'Frases':'Listening'}</h2></div><button data-eh="close">✕</button></div>${history.length?history.slice().reverse().map((idx,pos)=>{if(mode==='sentences'){const d=SENTENCES[idx] as any;return`<button class="exerciseHistoryItem" data-eh="review" data-index="${idx}"><b>${esc(d[1])}</b><span>Ejercicio ${idx+1}</span></button>`}const d=LISTENING[idx] as any,old=state.listeningHistory.find(x=>x.index===idx);return`<button class="exerciseHistoryItem" data-eh="review" data-index="${idx}"><b>${esc(d[2])}</b><span class="${old?.correct?'ehRight':'ehWrong'}">${old?.correct?'✓ Correcto':'✕ Incorrecto'} · ejercicio ${idx+1}</span></button>`}).join(''):'<div class="exerciseHistoryEmpty">Todavía no has terminado ejercicios en esta sección.</div>'}</div>`;document.body.appendChild(m)}
function click(e:MouseEvent){const t=(e.target as HTMLElement).closest('[data-eh]') as HTMLElement|null;if(!t)return;const a=t.dataset.eh;if(a==='history'){e.preventDefault();openHistory();return}if(a==='close'){document.querySelector('.exerciseHistoryModal')?.remove();return}if(a==='review'){reviewIndex=Number(t.dataset.index);sentenceShown=false;listenScript=false;document.querySelector('.exerciseHistoryModal')?.remove();render();return}if(!mode)return;const idx=reviewIndex??(mode==='sentences'?state.sentenceIndex:state.listeningIndex);if(mode==='sentences'){const d=SENTENCES[idx] as any;if(a==='sentence-show'){sentenceShown=true;render()}else if(a==='sentence-audio')speak(d[2]);else if(a==='sentence-next'){if(reviewIndex!==null){reviewIndex=null}else{state.sentenceHistory=uniq([...state.sentenceHistory,idx]);state.sentenceIndex=Math.min(idx+1,SENTENCES.length-1);save(state);addXp(5)}sentenceShown=false;render()}return}const d=LISTENING[idx] as any;if(a==='keyword')speak(t.dataset.text||'');else if(a==='pre-done'){listenPre=false;render()}else if(a==='listen-normal')speak(d[1],.82);else if(a==='listen-slow')speak(d[1],.62);else if(a==='answer'&&listenAnswer===null){listenAnswer=Number(t.dataset.j);if(reviewIndex===null){const correct=listenAnswer===d[4];state.listeningHistory=[...state.listeningHistory.filter(x=>x.index!==idx),{index:idx,correct,answer:listenAnswer}];save(state)}render()}else if(a==='script'){listenScript=!listenScript;render()}else if(a==='listen-next'){if(reviewIndex!==null){reviewIndex=null}else{state.listeningIndex=Math.min(idx+1,LISTENING.length-1);save(state);addXp(listenAnswer===d[4]?18:3)}listenPre=true;listenAnswer=null;listenScript=false;render()}}
function syncSection(){const next=current();if(next!==mode){mode=next;reviewIndex=null;sentenceShown=false;listenPre=true;listenAnswer=null;listenScript=false}if(mode)render()}

document.addEventListener('click',click,true);const observer=new MutationObserver(()=>{if(!applying)queueMicrotask(syncSection)});observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('storage',()=>{state=load();syncSection()});setTimeout(syncSection,0);
