import type {CorpusWord} from './corpus';

// Coverage safety net: high-transfer B1 words/chunks that can decide a TELC
// listening answer. Corpus vocabulary is never removed. The extra rows are
// only inserted when the concept is genuinely absent from the uploaded exams.
type Coverage=[string,string,'essential'|'useful'];
export const TELC_COVERAGE:Coverage[]=[
['Absage','cancelación','essential'],['Abfahrt','salida','essential'],['Ankunft','llegada','essential'],['Anmeldung','inscripción / registro','essential'],['Anschluss','conexión / enlace','essential'],['Antrag','solicitud / formulario','essential'],['Ausgang','salida','essential'],['Bedingung','condición','essential'],['Beschwerde','queja / reclamación','essential'],['Bestätigung','confirmación','essential'],['Betrag','importe / cantidad','essential'],['Bewerbung','solicitud / postulación','essential'],['Eintritt','entrada / acceso','essential'],['Erlaubnis','permiso','essential'],['Frist','plazo','essential'],['Gebühr','tasa / tarifa','essential'],['Gehalt','salario','essential'],['Gültigkeit','validez','essential'],['Kündigung','renuncia / despido / rescisión','essential'],['Lieferung','entrega','essential'],['Mietvertrag','contrato de alquiler','essential'],['Nachteil','desventaja','essential'],['Öffnungszeiten','horario de apertura','essential'],['Pflicht','obligación','essential'],['Preis','precio','essential'],['Rechnung','cuenta / factura','essential'],['Reklamation','reclamación','essential'],['Rückgabe','devolución','essential'],['Rücksendung','devolución / envío de vuelta','essential'],['Schaden','daño','essential'],['Termin','cita','essential'],['Umleitung','desvío','essential'],['Versicherung','seguro','essential'],['Verspätung','retraso','essential'],['Voraussetzung','requisito / condición previa','essential'],['Vorteil','ventaja','essential'],['Zuschlag','suplemento / recargo','essential'],
['absagen','cancelar','essential'],['anmelden','inscribirse / registrarse','essential'],['beantragen','solicitar','essential'],['bestätigen','confirmar','essential'],['kündigen','renunciar / despedir / rescindir','essential'],['stattfinden','tener lugar','essential'],['teilnehmen','participar','essential'],['umsteigen','hacer transbordo','essential'],['verschieben','aplazar / posponer','essential'],['verpassen','perder / no alcanzar','essential'],['vereinbaren','acordar / concertar','essential'],['zurückgeben','devolver','essential'],
// Listening decision verbs: cancellations, replacements, restrictions and changes.
['ausfallen','cancelarse / no realizarse','essential'],['entfallen','suprimirse / cancelarse','essential'],['ersetzen','sustituir / reemplazar','essential'],['sperren','cerrar / bloquear','essential'],['gesperrt','cerrado / bloqueado','essential'],['ändern','cambiar / modificar','essential'],['geändert','cambiado / modificado','essential'],['verlegen','trasladar / cambiar de fecha o lugar','essential'],['verlängern','prolongar / extender','essential'],['verkürzen','acortar','essential'],['steigen','subir / aumentar','essential'],['sinken','bajar / disminuir','essential'],['zunehmen','aumentar','essential'],['abnehmen','disminuir','essential'],['abfahren','salir / partir','essential'],['ankommen','llegar','essential'],['einsteigen','subir / entrar al transporte','essential'],['aussteigen','bajar / salir del transporte','essential'],
// Contrast, correction and logical pivots. These frequently flip richtig/falsch.
['allerdings','sin embargo / eso sí','essential'],['außerdem','además','essential'],['deshalb','por eso','essential'],['deswegen','por eso','essential'],['obwohl','aunque','essential'],['trotzdem','aun así / sin embargo','essential'],['sondern','sino','essential'],['während','mientras / durante','essential'],['wegen','a causa de / por','essential'],['falls','en caso de que / si','essential'],['stattdessen','en su lugar / en cambio','essential'],['jedoch','sin embargo','essential'],['dagegen','en cambio / contra eso','essential'],['daher','por eso / de ahí','essential'],['nämlich','pues / concretamente / porque','essential'],['zwar','ciertamente; usado en zwar … aber','essential'],
// Quantity/time thresholds: often the only difference between an option and audio.
['mindestens','como mínimo','essential'],['höchstens','como máximo','essential'],['ungefähr','aproximadamente','essential'],['insgesamt','en total','essential'],['jeweils','cada uno / respectivamente','essential'],['rechtzeitig','a tiempo','essential'],['voraussichtlich','previsiblemente / probablemente','essential'],['bereits','ya','essential'],['noch','todavía / aún','essential'],['erst','recién / solo a partir de','essential'],['fast','casi','essential'],['kaum','apenas','essential'],['genug','suficiente','essential'],['spätestens','a más tardar','essential'],['frühestens','como muy pronto','essential'],['vorher','antes / previamente','essential'],['nachher','después','essential'],['anschließend','a continuación','essential'],['inzwischen','mientras tanto / entretanto','essential'],['demnächst','próximamente','essential'],['sofort','inmediatamente','essential'],
// High-value chunks: learn the meaning as a unit, not word-by-word.
['nicht mehr','ya no','essential'],['noch nicht','todavía no','essential'],['erst ab','solo a partir de','essential'],['bis spätestens','a más tardar hasta','essential'],['mehr als','más de','essential'],['weniger als','menos de','essential'],['sowohl als auch','tanto … como','essential'],['weder noch','ni … ni','essential'],['nicht nur sondern auch','no solo … sino también','essential'],['fällt aus','se cancela / no se realiza','essential'],['findet statt','tiene lugar / se realiza','essential'],
// Status and instruction words common in announcements and selective listening.
['geschlossen','cerrado','essential'],['geöffnet','abierto','essential'],['verboten','prohibido','essential'],['erlaubt','permitido','essential'],['verfügbar','disponible','essential'],['ausverkauft','agotado','essential'],['kostenpflichtig','de pago / con coste','essential'],['kostenfrei','gratuito','essential'],['gültig','válido','essential'],['ungültig','no válido','essential'],['erforderlich','obligatorio / necesario','essential'],['notwendig','necesario','essential'],['empfohlen','recomendado','essential'],['beachten','tener en cuenta / prestar atención','essential'],['mitteilen','comunicar / informar','essential'],['Bescheid geben','avisar / informar','essential'],['sich melden','ponerse en contacto / avisar','essential'],
['Arbeitsplatz','puesto de trabajo','useful'],['Ausbildung','formación profesional','useful'],['Behörde','autoridad / oficina pública','useful'],['Erfahrung','experiencia','useful'],['Führerschein','licencia de conducir','useful'],['Gesundheit','salud','useful'],['Haushalt','hogar','useful'],['Miete','alquiler / arriendo','useful'],['Nachbar','vecino','useful'],['Unterkunft','alojamiento','useful'],['Umgebung','alrededores','useful'],['Umweltschutz','protección del medio ambiente','useful'],['Verkehr','tráfico / transporte','useful'],['Wohnung','departamento / vivienda','useful'],['Ernährung','alimentación','useful'],['Arbeitslosigkeit','desempleo','useful'],['Heimweh','añoranza','useful'],['Übersetzung','traducción','useful'],['Qualität','calidad','useful'],['Führungszeugnis','certificado de antecedentes / buena conducta','useful'],['Sprachnachweis','certificado de idioma','useful']
];

export const TELC_COVERAGE_ES:Record<string,string>=Object.fromEntries(TELC_COVERAGE.map(([de,es])=>[de.toLocaleLowerCase('de-DE'),es]));
export const TELC_ESSENTIAL=new Set(TELC_COVERAGE.filter(x=>x[2]==='essential').map(x=>x[0].toLocaleLowerCase('de-DE')));

export const TELC_COVERAGE_WORDS:CorpusWord[]=TELC_COVERAGE.map(([de,_es,tier],i)=>({
 id:`telc:${de.toLocaleLowerCase('de-DE')}`,de,
 // Listening-heavy synthetic signal deliberately pushes answer-changing concepts
 // near the front. Real corpus counts remain untouched for concepts already seen.
 freq:tier==='essential'?85:24,speaking:tier==='essential'?8:5,writing:tier==='essential'?6:4,listening:tier==='essential'?76:15,
 rank:4000+i,roi:tier==='essential'?100:82,category:'corpus'
}));
