import type {CorpusWord} from './corpus';

// Coverage safety net: high-transfer B1 words that can decide a TELC answer.
// This does NOT replace or remove corpus vocabulary. It only adds genuinely
// absent concepts so the deck is not overfit to the uploaded practice exams.
type Coverage=[string,string,'essential'|'useful'];
export const TELC_COVERAGE:Coverage[]=[
['Absage','cancelación','essential'],['Abfahrt','salida','essential'],['Ankunft','llegada','essential'],['Anmeldung','inscripción / registro','essential'],['Anschluss','conexión / enlace','essential'],['Antrag','solicitud / formulario','essential'],['Ausgang','salida','essential'],['Bedingung','condición','essential'],['Beschwerde','queja / reclamación','essential'],['Bestätigung','confirmación','essential'],['Betrag','importe / cantidad','essential'],['Bewerbung','solicitud / postulación','essential'],['Eintritt','entrada / acceso','essential'],['Erlaubnis','permiso','essential'],['Frist','plazo','essential'],['Gebühr','tasa / tarifa','essential'],['Gehalt','salario','essential'],['Gültigkeit','validez','essential'],['Kündigung','renuncia / despido / rescisión','essential'],['Lieferung','entrega','essential'],['Mietvertrag','contrato de alquiler','essential'],['Nachteil','desventaja','essential'],['Öffnungszeiten','horario de apertura','essential'],['Pflicht','obligación','essential'],['Preis','precio','essential'],['Rechnung','cuenta / factura','essential'],['Reklamation','reclamación','essential'],['Rückgabe','devolución','essential'],['Rücksendung','devolución / envío de vuelta','essential'],['Schaden','daño','essential'],['Termin','cita','essential'],['Umleitung','desvío','essential'],['Versicherung','seguro','essential'],['Verspätung','retraso','essential'],['Voraussetzung','requisito / condición previa','essential'],['Vorteil','ventaja','essential'],['Zuschlag','suplemento / recargo','essential'],
['absagen','cancelar','essential'],['anmelden','inscribirse / registrarse','essential'],['beantragen','solicitar','essential'],['bestätigen','confirmar','essential'],['kündigen','renunciar / despedir / rescindir','essential'],['stattfinden','tener lugar','essential'],['teilnehmen','participar','essential'],['umsteigen','hacer transbordo','essential'],['verschieben','aplazar / posponer','essential'],['verpassen','perder / no alcanzar','essential'],['vereinbaren','acordar / concertar','essential'],['zurückgeben','devolver','essential'],
['allerdings','sin embargo / eso sí','essential'],['außerdem','además','essential'],['deshalb','por eso','essential'],['deswegen','por eso','essential'],['obwohl','aunque','essential'],['trotzdem','aun así / sin embargo','essential'],['sondern','sino','essential'],['während','mientras / durante','essential'],['wegen','a causa de / por','essential'],['falls','en caso de que / si','essential'],['mindestens','como mínimo','essential'],['höchstens','como máximo','essential'],['ungefähr','aproximadamente','essential'],['rechtzeitig','a tiempo','essential'],['voraussichtlich','previsiblemente / probablemente','essential'],['bereits','ya','essential'],['noch','todavía / aún','essential'],['erst','recién / primero','essential'],['fast','casi','essential'],['kaum','apenas','essential'],['genug','suficiente','essential'],['geschlossen','cerrado','essential'],['geöffnet','abierto','essential'],['verboten','prohibido','essential'],['erlaubt','permitido','essential'],
['Arbeitsplatz','puesto de trabajo','useful'],['Ausbildung','formación profesional','useful'],['Behörde','autoridad / oficina pública','useful'],['Erfahrung','experiencia','useful'],['Führerschein','licencia de conducir','useful'],['Gesundheit','salud','useful'],['Haushalt','hogar','useful'],['Miete','alquiler / arriendo','useful'],['Nachbar','vecino','useful'],['Unterkunft','alojamiento','useful'],['Umgebung','alrededores','useful'],['Umweltschutz','protección del medio ambiente','useful'],['Verkehr','tráfico / transporte','useful'],['Wohnung','departamento / vivienda','useful'],['Ernährung','alimentación','useful'],['Arbeitslosigkeit','desempleo','useful'],['Heimweh','añoranza','useful'],['Übersetzung','traducción','useful'],['Qualität','calidad','useful'],['Führungszeugnis','certificado de antecedentes / buena conducta','useful'],['Sprachnachweis','certificado de idioma','useful']
];

export const TELC_COVERAGE_ES:Record<string,string>=Object.fromEntries(TELC_COVERAGE.map(([de,es])=>[de.toLocaleLowerCase('de-DE'),es]));
export const TELC_ESSENTIAL=new Set(TELC_COVERAGE.filter(x=>x[2]==='essential').map(x=>x[0].toLocaleLowerCase('de-DE')));

export const TELC_COVERAGE_WORDS:CorpusWord[]=TELC_COVERAGE.map(([de,_es,tier],i)=>({
 id:`telc:${de.toLocaleLowerCase('de-DE')}`,de,
 // Synthetic frequency is only a priority signal. Real corpus counts always win
 // because these rows are inserted only when the word is genuinely absent.
 freq:tier==='essential'?70:24,speaking:tier==='essential'?10:5,writing:tier==='essential'?8:4,listening:tier==='essential'?52:15,
 rank:4000+i,roi:tier==='essential'?98:82,category:'corpus'
}));
