import{loadCorpusWords,loadSpanishMap}from'./corpus';
import{officialTelcSpanish}from'./telcOfficialSpanish';
import{EXAM_BOOST_ES,EXAM_BOOST_WORDS}from'./examVocabBoost';
import{TELC_COVERAGE_ES,TELC_COVERAGE_WORDS}from'./telcCoverageBoost';
import{groupCorpusFamilies}from'./vocabFamilies';
import{VERIFIED_SPANISH_AUDIT}from'./verifiedSpanishAudit';
import{VERIFIED_SPANISH_AUDIT_LARGE}from'./verifiedSpanishAuditLarge';
import{VERIFIED_SPANISH_AUDIT_LARGE2}from'./verifiedSpanishAuditLarge2';
import{VERIFIED_SPANISH_AUDIT_LARGE3}from'./verifiedSpanishAuditLarge3';
import{VERIFIED_SPANISH_AUDIT_LARGE4}from'./verifiedSpanishAuditLarge4';
import{VERIFIED_SPANISH_AUDIT_LARGE5}from'./verifiedSpanishAuditLarge5';

const FALLBACK_CACHE='telcb1-complete-es-v12';
const CORPUS_CACHE='telcb1-corpus-es-v14';
const AUDIT_KEY='telcb1-translation-qc-v12';
const GOOGLE='https://translate.googleapis.com/translate_a/single?client=gtx&sl=de&tl=es&dt=t&q=';
const MYMEMORY='https://api.mymemory.translated.net/get?langpair=de%7Ces&q=';
function key(de:string){return de.toLocaleLowerCase('de-DE').trim()}
function read(k:string):Record<string,string>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}}
function save(k:string,x:any){try{localStorage.setItem(k,JSON.stringify(x))}catch{}}
function clean(x:string){return String(x||'').replace(/^[-–—\s]+|[-–—\s]+$/g,'').replace(/\s+/g,' ').trim()}
function suspicious(de:string,es:string){const d=key(de),s=clean(es).toLocaleLowerCase('es-ES');return !s||s===d||s.length>100||/https?:|<[^>]+>|\b(jota|ápice|miaja|adarme|maravedí|ochavo|ardite)\b/i.test(s)}
function targets(words:{de:string}[]){const out:{de:string}[]=[],seen=new Set<string>();for(const w of [...words,...EXAM_BOOST_WORDS,...TELC_COVERAGE_WORDS]){const k=key(w.de);if(!seen.has(k)){seen.add(k);out.push({de:w.de})}}return out}
const COMMON_B1:Record<string,string>={'bekommen':'recibir','machen':'hacer','gehen':'ir','fahren':'ir / conducir','laufen':'caminar / correr','treffen':'encontrarse / quedar','meinen':'opinar / querer decir','finden':'encontrar / parecer','sollen':'deber','dürfen':'poder / tener permiso','müssen':'deber / tener que','mögen':'gustar','brauchen':'necesitar','passen':'quedar bien / encajar','ziehen':'tirar / mudarse','halten':'parar / sostener','stellen':'poner / colocar','legen':'poner / colocar','setzen':'sentar / poner','lassen':'dejar','tragen':'llevar','holen':'ir a buscar / recoger','bringen':'traer / llevar','abholen':'recoger','bestellen':'pedir','zahlen':'pagar','kosten':'costar','verdienen':'ganar / cobrar','kündigen':'renunciar / despedir','anmelden':'inscribirse / registrarse','absagen':'cancelar','zusagen':'aceptar / confirmar','vereinbaren':'acordar / concertar','verschieben':'aplazar / posponer','teilnehmen':'participar','übernehmen':'hacerse cargo de / asumir','erledigen':'hacer / resolver','besorgen':'conseguir / comprar','sich erinnern':'recordar','erinnern':'recordar','sich kümmern':'ocuparse de','kümmern':'ocuparse de','sich bewerben':'postular / solicitar','bewerben':'postular / solicitar','sich beschweren':'quejarse','beschweren':'quejarse','sich entscheiden':'decidirse','entscheiden':'decidir','sich treffen':'encontrarse / quedar','sich fühlen':'sentirse','fühlen':'sentir','sich interessieren':'interesarse','interessieren':'interesar','teilen':'compartir','luft':'aire','termin':'cita','wohnung':'departamento / vivienda','miete':'alquiler / arriendo','vermieter':'propietario / arrendador','nachbar':'vecino','umzug':'mudanza','arbeit':'trabajo','arbeitsplatz':'puesto de trabajo','beruf':'profesión','gehalt':'salario','ausbildung':'formación profesional','prüfung':'examen','aufgabe':'tarea / ejercicio','übung':'ejercicio / práctica','nachricht':'mensaje','brief':'carta','rechnung':'cuenta / factura','angebot':'oferta','günstig':'económico','teuer':'caro','gesund':'saludable','krank':'enfermo','arzt':'médico','hilfe':'ayuda','verkehr':'tráfico','fahrkarte':'boleto / pasaje','verspätung':'retraso','urlaub':'vacaciones','unterkunft':'alojamiento','umgebung':'alrededores','möglichkeit':'posibilidad','erfahrung':'experiencia','meinung':'opinión','vorteil':'ventaja','nachteil':'desventaja','wichtig':'importante','möglich':'posible','wahrscheinlich':'probablemente','eigentlich':'en realidad','trotzdem':'aun así','außerdem':'además','deswegen':'por eso','deshalb':'por eso','obwohl':'aunque','falls':'en caso de que / si','während':'mientras / durante','gegenüber':'frente a / enfrente de'};
async function translateGoogle(de:string){const r=await fetch(GOOGLE+encodeURIComponent(de),{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const d=await r.json();return clean((d?.[0]||[]).map((x:any)=>x?.[0]||'').join(''))}
async function translateMemory(de:string){const r=await fetch(MYMEMORY+encodeURIComponent(de),{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const d=await r.json();return clean(d?.responseData?.translatedText||'')}
async function translateBrowser(de:string){try{const T=(globalThis as any).Translator;if(!T)return'';const availability=await T.availability?.({sourceLanguage:'de',targetLanguage:'es'});if(availability==='unavailable')return'';const tr=await T.create({sourceLanguage:'de',targetLanguage:'es'});const x=clean(await tr.translate(de));tr.destroy?.();return suspicious(de,x)?'':x}catch{return''}}
async function translateOne(de:string){try{const a=await translateGoogle(de);if(!suspicious(de,a))return a}catch{}try{const b=await translateMemory(de);if(!suspicious(de,b))return b}catch{}const c=await translateBrowser(de);if(c)return c;return''}
async function worker(queue:string[],cache:Record<string,string>){while(queue.length){const de=queue.shift()!,k=key(de);if(cache[k])continue;const es=await translateOne(de);if(es)cache[k]=es}}
export async function completeSpanishTranslations(words:{de:string}[],existing:Record<string,string>){
 const all=targets(words),human={...VERIFIED_SPANISH_AUDIT,...VERIFIED_SPANISH_AUDIT_LARGE,...VERIFIED_SPANISH_AUDIT_LARGE2,...VERIFIED_SPANISH_AUDIT_LARGE3,...VERIFIED_SPANISH_AUDIT_LARGE4,...VERIFIED_SPANISH_AUDIT_LARGE5},staticChecked={...TELC_COVERAGE_ES,...EXAM_BOOST_ES,...human};const out:Record<string,string>={...existing,...staticChecked};let official=0,common=0,existingKept=0,fallback=0,manuallyAudited=0;
 for(const w of all){const k=key(w.de),telc=officialTelcSpanish(w.de),commonGloss=COMMON_B1[k]||COMMON_B1[k.replace(/^sich\s+/,'')];if(human[k]){out[k]=human[k];manuallyAudited++;continue}if(telc){out[k]=telc;official++;continue}if(staticChecked[k]){out[k]=staticChecked[k];continue}if(commonGloss){out[k]=commonGloss;common++;continue}if(out[k]&&!suspicious(w.de,out[k]))existingKept++;else delete out[k]}
 const cache={...read(FALLBACK_CACHE),...out};for(let pass=0;pass<6;pass++){const missing=all.filter(w=>!cache[key(w.de)]).map(w=>w.de);if(!missing.length)break;const queue=[...missing];await Promise.all(Array.from({length:2},()=>worker(queue,cache)));save(FALLBACK_CACHE,cache);if(pass<5&&queue.length)await new Promise(r=>setTimeout(r,300*(pass+1)))}
 for(const w of all){const k=key(w.de);if(!out[k]&&cache[k]&&!suspicious(w.de,cache[k])){out[k]=cache[k];fallback++}}
 save(FALLBACK_CACHE,out);save(AUDIT_KEY,{checked:all.length,translated:all.filter(w=>!!out[key(w.de)]).length,missing:all.filter(w=>!out[key(w.de)]).length,official,common,existingKept,fallback,manuallyAudited,coverage:all.length?Math.round(all.filter(w=>!!out[key(w.de)]).length/all.length*10000)/100:100,at:new Date().toISOString(),referenceHierarchy:['human audited','official TELC B1 Spanish','curated exam/TELC safety net','reviewed B1','validated existing dictionary','multi-provider fallback']});return out
}
export async function bootstrapCompleteTranslations(){const baseWords=await loadCorpusWords();const families=groupCorpusFamilies(baseWords);const displayed=families.flatMap(f=>[{de:f.lemma},...f.forms.map(de=>({de}))]);const all=targets([...baseWords,...displayed]);const base=await loadSpanishMap(all);return await completeSpanishTranslations(all,base)}